config/routes.rb
Rails.application.routes.draw do
  resources :resenas
  resources :reviews
  devise_for :users
  get 'welcome/index'

  get 'welcome/Index'

  resources :topics
  resources :careers
  resources :professors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/resena.rb
class Resena < ApplicationRecord
  belongs_to :user
  belongs_to :professor
end

app/controllers/resenas_controller.rb
class ResenasController < ApplicationController
  before_action :set_resena, only: [:show, :edit, :update, :destroy]

  # GET /resenas
  # GET /resenas.json
  def index
    @resenas = Resena.all
  end

  # GET /resenas/1
  # GET /resenas/1.json
  def show
  end

  # GET /resenas/new
  def new
    @resena = Resena.new
  end

  # GET /resenas/1/edit
  def edit
  end

  # POST /resenas
  # POST /resenas.json
  def create
    @resena = Resena.new(resena_params)

    respond_to do |format|
      if @resena.save
        format.html { redirect_to @resena, notice: 'Resena was successfully created.' }
        format.json { render :show, status: :created, location: @resena }
      else
        format.html { render :new }
        format.json { render json: @resena.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resenas/1
  # PATCH/PUT /resenas/1.json
  def update
    respond_to do |format|
      if @resena.update(resena_params)
        format.html { redirect_to @resena, notice: 'Resena was successfully updated.' }
        format.json { render :show, status: :ok, location: @resena }
      else
        format.html { render :edit }
        format.json { render json: @resena.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resenas/1
  # DELETE /resenas/1.json
  def destroy
    @resena.destroy
    respond_to do |format|
      format.html { redirect_to resenas_url, notice: 'Resena was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resena
      @resena = Resena.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resena_params
      params.require(:resena).permit(:title, :score, :description, :user_id, :professor_id)
    end
end

app/helpers/resenas_helper.rb
module ResenasHelper
end

app/views/resenas/_form.html.erb
<%= form_with(model: resena, local: true) do |form| %>
  <% if resena.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resena.errors.count, "error") %> prohibited this resena from being saved:</h2>

      <ul>
      <% resena.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :resena_title %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :resena_score %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :resena_description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :resena_user_id %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id, id: :resena_professor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resenas/edit.html.erb
<h1>Editing Resena</h1>

<%= render 'form', resena: @resena %>

<%= link_to 'Show', @resena %> |
<%= link_to 'Back', resenas_path %>

app/views/resenas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resenas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Score</th>
      <th>Description</th>
      <th>User</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resenas.each do |resena| %>
      <tr>
        <td><%= resena.title %></td>
        <td><%= resena.score %></td>
        <td><%= resena.description %></td>
        <td><%= resena.user %></td>
        <td><%= resena.professor %></td>
        <td><%= link_to 'Show', resena %></td>
        <td><%= link_to 'Edit', edit_resena_path(resena) %></td>
        <td><%= link_to 'Destroy', resena, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resena', new_resena_path %>

app/views/resenas/new.html.erb
<h1>New Resena</h1>

<%= render 'form', resena: @resena %>

<%= link_to 'Back', resenas_path %>

app/views/resenas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resena.title %>
</p>

<p>
  <strong>Score:</strong>
  <%= @resena.score %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resena.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @resena.user %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @resena.professor %>
</p>

<%= link_to 'Edit', edit_resena_path(@resena) %> |
<%= link_to 'Back', resenas_path %>