config/routes.rb
Rails.application.routes.draw do
  resources :resenas
  resources :reviews
  devise_for :users
  get 'welcome/index'

  get 'welcome/Index'

  resources :topics
  resources :careers
  resources :professors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :professors
  validates :name, presence: true, uniqueness: true
  validates :semester, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_admin!, only: [:destroy, :create]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    #@topic = Topic.new(topic_params)
    @topic = current_user.topics.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :semester)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :topic_name %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.number_field :semester, id: :topic_semester %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.name, topic %></td>
        <td><%= topic.semester %></td>
        <% if user_signed_in? %>
          <% if current_user.is_admin? %>
            <td><%= link_to 'Show', topic %></td>
            <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
            <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <% if current_user.is_admin? %>
    <%= link_to 'New Topic', new_topic_path %>
  <% end %>
<% end %>

app/views/topics/new.html.erb
<h1>Nueva materia</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1 class="masthead-subheading mb-0"><%= @topic.name %></h1>
</div>

<h5 style="padding-top: 30px">
  <strong>Semester:</strong>
  <%= @topic.semester %>
</h5>

<div style="padding-top: 5px">
  <%= Prototipo.getLorem(@topic.id) %>
</div>

<div class="jcontainer">
  <h3 class="masthead-subheading mb-0">Profesores que imparten</h3>
  <ul>
    <% @topic.professors.each do |professor|%>
      <li>
        <%=link_to professor.name, professor%>
      </li>
    <%end%>
  </ul>
</div>

<% if user_signed_in? %>
  <% if current_user.is_admin? %>
    <div class="jcontainer" style="margin-top: 20%">
      <%= link_to 'Edit', edit_topic_path(@topic) %> |
      <%= link_to 'Back', topics_path %>
    </div>
  <% end %>
<% end %>