config/routes.rb
Rails.application.routes.draw do
  resources :resenas
  resources :reviews
  devise_for :users
  get 'welcome/index'

  get 'welcome/Index'

  resources :topics
  resources :careers
  resources :professors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/partials/_navigation.html.erb
<header>

  <nav class="black white large-padding bold-font">
    <ul style="list-style-type: none" class="no-list row center-xs middle-xs">
      <li class="col-xs ">
        <%= link_to image_tag('logo-one-line.png', width: "50%"), root_path%>
      </li>
      <li class="col-xs">
        <%= link_to "Profesores", professors_path%>
      </li>
      <li class="col-xs">
        <%= link_to "Materias", topics_path%>
      </li>
      <% if user_signed_in? %>
        <li class="col-xs" style="">
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%>
        </li>
        <li class="col-xs">
          <%= link_to "Cambiar contraseña", edit_user_registration_path%>
        </li>
        <li class="col-xs">
          <%= link_to "Agregar materia", new_topic_path%>
        </li>
        <li class="col-xs">
          <%= link_to "Agregar carrera", new_career_path%>
        </li>
      <%else%>
        <li class="col-xs">
          <%= link_to "Iniciar sesión", new_user_session_path%>
        </li>
        <li class="col-xs">
          <%= link_to "Registro", new_user_registration_path%>
        </li>
      <%end%>
    </ul>
  </nav>
</header>