config/routes.rb
Rails.application.routes.draw do
  resources :resenas
  resources :reviews
  devise_for :users
  get 'welcome/index'

  get 'welcome/Index'

  resources :topics
  resources :careers
  resources :professors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :topics
  has_many :reviews
  validates :name, presence: true
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_admin!, only: [:destroy, :create]
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @review = Review.new
    @textp = Prototipo.getLorem(params[:id])
    @image = Prototipo.getImage(params[:id])
end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = current_user.professors.new(professor_params)
    #@professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
      @@professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :professor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>
<% @count = 0 %>
<% @professors.each do |professor| %>
  <% if @count > 0 %>
  <div style="padding-top: 210px !important;">
  <% else %>
    <div>
    <% @count = 1 %>
  <% end %>
    <div class="two-div-container">
      <div class="one">
        <h3 class="masthead-subheading mb-0"><%= professor.name %></h3>
        <div style="padding-top: 10px"></div>
        <%= image_tag(Prototipo.getImage(professor.id), class:"img-fluid rounded-circle", size: 400)%>
      </div>
      <div class="two">
        <p style="padding-top: 60px">
          <%= Prototipo.getLorem(professor.id)[0..300] %>
        </p>
        <p>
          <%= link_to 'Ver profesor', professor %>
        </p>
      </div>
    </div>
  </div>
<% end %>



<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>Nuevo profesor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1 class="masthead-subheading mb-0"><%= @professor.name %></h1>
</div>

<div style="margin-top: 20px" class="two-div-container">
  <div class="one">
    <%= image_tag(@image, class:"img-fluid rounded-circle", size: 400 )%>
  </div>
  <div class="two">
    <p>
      <%= @textp %>
    </p>
  </div>
</div>

<div class="jcontainer" style="padding-top: 50px">
  <h2 class="masthead-subheading mb-0">Clases que imparte</h2>
  <ul>
    <% @professor.topics.each do |topic|%>
      <li>
        <%=link_to topic.name, topic%>
      </li>
    <%end%>
  </ul>
</div>

<div class="field">
  <h3 class="masthead-subheading mb-0" style="margin-top: 5%">Reseñas</h3>
  <div class="reviews-container">
      <% @professor.reviews.each do |review|%>
        <div class="review-row">
            <div class="review-title">
              <p>Titulo: <%=review.title%></p>
            </div>
            <div class="review-score">
              <p>Calificación: <%=review.score%></p>
            </div>
            <div class="review-description">
              <p>Descripción: <%=review.description%></p>
            </div>
            <div class="review-author">
              <p>Autor: <%= review.user.email %></p>
            </div>
        </div>
      <%end%>
  </div>
</div>

<div style="padding-top: 30px">
  <%= render 'reviews/form' %>
</div>



<% if user_signed_in? %>
  <% if current_user.is_admin? %>
    <div class="jcontainer" style="margin-top: 20%">
      <%= link_to 'Edit', edit_professor_path(@professor) %> |
      <%= link_to 'Back', professors_path %>
    </div>
  <% end %>
<% end %>